name: Desafio Matheus CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18.0
        env:
          POSTGRES_DB: Desafio
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: 'maven'

    - name: Run tests
      run: mvn test

    - name: Build API desafio
      run: mvn spring-boot:build-image

    - name: Docker Compose Build
      run: docker compose build

    - name: Tag Docker Images
      run: |
        docker tag ${{secrets.DOCKER_USERNAME}}/desafio:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/desafio:latest
        docker tag ${{secrets.DOCKER_USERNAME}}/desafio:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/desafio:${{github.RUN_ID}}

    - name: Push Docker Images to Docker Hub
      run: |
        docker push ${{secrets.DOCKER_USERNAME}}/desafio:latest
        docker push ${{secrets.DOCKER_USERNAME}}/desafio:${{github.RUN_ID}}
